# Generated by Django 2.2.8 on 2019-12-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secur_name', models.CharField(max_length=250)),
                ('price_open', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date open')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_close', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='date close')),
                ('open_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Users'),
        ),
    ]
