# Generated by Django 2.2.6 on 2019-12-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='quantity',
            new_name='quantity_open',
        ),
        migrations.RenameField(
            model_name='trade_close',
            old_name='quantity',
            new_name='quantity_close',
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
