# Generated by Django 2.2.6 on 2019-12-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20191209_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='journal.Users'),
        ),
        migrations.AlterField(
            model_name='trade_close',
            name='open_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='journal.Trade'),
        ),
    ]
